export const GET_WEATHER_BY_LOCATION_COMPLETE = "GET_WEATHER_BY_LOCATION_COMPLETE";
export const GET_WEATHER_BY_LOCATION_LOADING = "GET_WEATHER_BY_LOCATION_LOADING";
export const GET_WEATHER_BY_LOCATION_ERROR = "GET_WEATHER_BY_LOCATION_ERROR";
export const SELECT_FORECAST = "SELECT_FORECAST";
export const HOURLY = "";
export const DAILY = "daily";
